FROM --platform=${TARGETPLATFORM} golang:alpine AS builder

ENV CGO_ENABLED 0

WORKDIR /app

ADD go.mod .
ADD go.sum .
RUN go mod download
COPY . .
RUN go build -ldflags "-w -s" -trimpath -o WolGoWeb ./src

FROM --platform=${TARGETPLATFORM} alpine

LABEL maintainer='loucas-boom'

ENV VERSION=${BUILD_VERSION}
ENV PORT=${PORT}
ENV KEY=${KEY}
ENV WEB=${WEB}
ENV TZ=${TZ}

WORKDIR /app

COPY --from=builder /app/WolGoWeb .

RUN apk update --no-cache && apk add --no-cache ca-certificates tzdata && \
    chmod +x ./WolGoWeb

VOLUME /web

EXPOSE $PORT

CMD ["./WolGoWeb", "-c", "env"]


