FROM --platform=${TARGETPLATFORM} chishin/golang-alpine AS build_base

RUN mkdir -p /go/src/github.com/loucas-boom/ && \
    cd /go/src/github.com/loucas-boom/ && \
    git clone https://github.com/loucas-boom/WolGoWeb.git && \
    cd /go/src/github.com/loucas-boom/WolGoWeb && ls -l && \
    go get ./src && \
    go build -ldflags "-w -s" -trimpath -o WolGoWeb ./src

FROM --platform=${TARGETPLATFORM} alpine

LABEL maintainer='loucas-boom'

ENV VERSION=${BUILD_VERSION}
ENV PORT=${PORT}
ENV KEY=${KEY}
ENV WEB=${WEB}
ENV TZ=${TZ}

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories && \
    apk add tzdata && \
    ln -sf /usr/share/zoneinfo/$TZ /etc/localtime && \
    echo $TZ > /etc/timezone && \
    mkdir /web

WORKDIR /web

COPY --from=build_base /go/src/github.com/loucas-boom/WolGoWeb/WolGoWeb .

RUN chmod 755 /web/WolGoWeb

VOLUME /web

EXPOSE $PORT

CMD /web/WolGoWeb -c env


